// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IoBuild.IAM.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AutenticacionDeUsuariosFeature : object, Xunit.IClassFixture<AutenticacionDeUsuariosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Authentication.feature"
#line hidden
        
        public AutenticacionDeUsuariosFeature(AutenticacionDeUsuariosFeature.FixtureData fixtureData, IoBuild_IAM_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Autenticacion de Usuarios", "  Como usuario del sistema IoBuild\r\n  Quiero poder autenticarme con mi email y co" +
                    "ntrasena\r\n  Para acceder a las funcionalidades segun mi rol", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
#line 7
    testRunner.Given("el sistema tiene un usuario registrado con email \"builder@iobuilt.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.And("su rol es \"PropertyManager\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    testRunner.And("su contrasena es \"SecurePass123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Inicio de sesion exitoso con credenciales validas")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticacion de Usuarios")]
        [Xunit.TraitAttribute("Description", "Inicio de sesion exitoso con credenciales validas")]
        [Xunit.TraitAttribute("Category", "US44")]
        [Xunit.TraitAttribute("Category", "QA-1")]
        [Xunit.TraitAttribute("Category", "Critical")]
        public void InicioDeSesionExitosoConCredencialesValidas()
        {
            string[] tagsOfScenario = new string[] {
                    "US44",
                    "QA-1",
                    "Critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inicio de sesion exitoso con credenciales validas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 13
    testRunner.Given("el usuario no esta autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "email",
                            "builder@iobuilt.com"});
                table1.AddRow(new string[] {
                            "password",
                            "SecurePass123!"});
#line 14
    testRunner.When("el usuario envia una solicitud POST a \"/api/v1/authentication/sign-in\"", ((string)(null)), table1, "When ");
#line hidden
#line 18
    testRunner.Then("la respuesta debe tener codigo 200 OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
    testRunner.And("la respuesta debe contener un token JWT valido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
    testRunner.And("el token debe expirar en 7 dias", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
    testRunner.And("el token debe incluir el Claim \"role\" con valor \"PropertyManager\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Inicio de sesion fallido por contrasena incorrecta")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticacion de Usuarios")]
        [Xunit.TraitAttribute("Description", "Inicio de sesion fallido por contrasena incorrecta")]
        [Xunit.TraitAttribute("Category", "US44")]
        [Xunit.TraitAttribute("Category", "QA-1")]
        [Xunit.TraitAttribute("Category", "Security")]
        public void InicioDeSesionFallidoPorContrasenaIncorrecta()
        {
            string[] tagsOfScenario = new string[] {
                    "US44",
                    "QA-1",
                    "Security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inicio de sesion fallido por contrasena incorrecta", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 25
    testRunner.Given("el usuario no esta autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "email",
                            "builder@iobuilt.com"});
                table2.AddRow(new string[] {
                            "password",
                            "WrongPassword456!"});
#line 26
    testRunner.When("el usuario envia una solicitud POST a \"/api/v1/authentication/sign-in\"", ((string)(null)), table2, "When ");
#line hidden
#line 30
    testRunner.Then("la respuesta debe tener codigo 401 Unauthorized", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Acceso a endpoint protegido sin token retorna 401")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticacion de Usuarios")]
        [Xunit.TraitAttribute("Description", "Acceso a endpoint protegido sin token retorna 401")]
        [Xunit.TraitAttribute("Category", "QA-1")]
        [Xunit.TraitAttribute("Category", "Security")]
        public void AccesoAEndpointProtegidoSinTokenRetorna401()
        {
            string[] tagsOfScenario = new string[] {
                    "QA-1",
                    "Security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acceso a endpoint protegido sin token retorna 401", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 34
    testRunner.Given("el usuario no esta autenticado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 35
    testRunner.When("el usuario envia una solicitud GET a \"/api/v1/users\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
    testRunner.Then("la respuesta debe tener codigo 401 Unauthorized", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AutenticacionDeUsuariosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AutenticacionDeUsuariosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
