// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IoBuild.Projects.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GestionDeProyectosYClientesFeature : object, Xunit.IClassFixture<GestionDeProyectosYClientesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ProjectsManagement.feature"
#line hidden
        
        public GestionDeProyectosYClientesFeature(GestionDeProyectosYClientesFeature.FixtureData fixtureData, IoBuild_Projects_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Gestion de Proyectos y Clientes", "  Como un Property Manager\r\n  Quiero gestionar proyectos de construccion y sus cl" +
                    "ientes asociados\r\n  Para administrar el portafolio de propiedades", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
#line 7
    testRunner.Given("el usuario esta autenticado como \"PropertyManager\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.And("existen 3 proyectos registrados en el sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar todos los proyectos")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestion de Proyectos y Clientes")]
        [Xunit.TraitAttribute("Description", "Listar todos los proyectos")]
        [Xunit.TraitAttribute("Category", "CRN-1")]
        public void ListarTodosLosProyectos()
        {
            string[] tagsOfScenario = new string[] {
                    "CRN-1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar todos los proyectos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 12
    testRunner.When("el usuario envia una solicitud GET a \"/api/v1/projects\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
    testRunner.Then("la respuesta debe tener codigo 200 OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
    testRunner.And("la respuesta debe contener una lista de proyectos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
    testRunner.And("cada proyecto debe tener los campos: id, name, description, location, totalUnits," +
                        " status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Crear un nuevo proyecto")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestion de Proyectos y Clientes")]
        [Xunit.TraitAttribute("Description", "Crear un nuevo proyecto")]
        [Xunit.TraitAttribute("Category", "CRN-1")]
        public void CrearUnNuevoProyecto()
        {
            string[] tagsOfScenario = new string[] {
                    "CRN-1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Crear un nuevo proyecto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "name",
                            "Edificio Green Tower"});
                table1.AddRow(new string[] {
                            "description",
                            "Proyecto sostenible"});
                table1.AddRow(new string[] {
                            "location",
                            "Miraflores"});
                table1.AddRow(new string[] {
                            "totalUnits",
                            "20"});
#line 19
    testRunner.When("el usuario envia una solicitud POST a \"/api/v1/projects\"", ((string)(null)), table1, "When ");
#line hidden
#line 25
    testRunner.Then("la respuesta debe tener codigo 201 Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
    testRunner.And("la respuesta debe incluir el ID del nuevo proyecto", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Asignar un cliente a un proyecto")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestion de Proyectos y Clientes")]
        [Xunit.TraitAttribute("Description", "Asignar un cliente a un proyecto")]
        [Xunit.TraitAttribute("Category", "CRN-1")]
        public void AsignarUnClienteAUnProyecto()
        {
            string[] tagsOfScenario = new string[] {
                    "CRN-1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Asignar un cliente a un proyecto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 30
    testRunner.Given("existe un proyecto con ID 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "fullName",
                            "Juan Perez"});
                table2.AddRow(new string[] {
                            "projectId",
                            "1"});
                table2.AddRow(new string[] {
                            "email",
                            "juan@example.com"});
#line 31
    testRunner.When("el usuario envia una solicitud POST a \"/api/v1/clients\"", ((string)(null)), table2, "When ");
#line hidden
#line 36
    testRunner.Then("la respuesta debe tener codigo 201 Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
    testRunner.And("el cliente debe estar asociado al proyecto ID 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GestionDeProyectosYClientesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GestionDeProyectosYClientesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
