// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IoBuild.Subscriptions.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RenovacionDePlanDeSuscripcionFeature : object, Xunit.IClassFixture<RenovacionDePlanDeSuscripcionFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SubscriptionRenewal.feature"
#line hidden
        
        public RenovacionDePlanDeSuscripcionFeature(RenovacionDePlanDeSuscripcionFeature.FixtureData fixtureData, IoBuild_Subscriptions_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Renovacion de Plan de Suscripcion", "  Como un Property Manager\r\n  Quiero renovar mi plan activo\r\n  Para asegurar la c" +
                    "ontinuidad del servicio", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
#line 7
    testRunner.Given("el usuario esta autenticado como \"PropertyManager\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.And("el usuario tiene un plan \"Professional\" activo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    testRunner.And("la pasarela de pagos Stripe esta configurada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Crear sesion de pago para renovar plan")]
        [Xunit.TraitAttribute("FeatureTitle", "Renovacion de Plan de Suscripcion")]
        [Xunit.TraitAttribute("Description", "Crear sesion de pago para renovar plan")]
        [Xunit.TraitAttribute("Category", "US31")]
        [Xunit.TraitAttribute("Category", "QA-3")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public void CrearSesionDePagoParaRenovarPlan()
        {
            string[] tagsOfScenario = new string[] {
                    "US31",
                    "QA-3",
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Crear sesion de pago para renovar plan", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "planId",
                            "2"});
                table1.AddRow(new string[] {
                            "builderId",
                            "1"});
#line 13
    testRunner.When("el usuario envia una solicitud POST a \"/api/v1/subscriptions/payments/create-sess" +
                        "ion\"", ((string)(null)), table1, "When ");
#line hidden
#line 17
    testRunner.Then("la respuesta debe tener codigo 200 OK", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
    testRunner.And("la respuesta debe contener una URL de checkout de Stripe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Confirmar pago exitoso y activar suscripcion")]
        [Xunit.TraitAttribute("FeatureTitle", "Renovacion de Plan de Suscripcion")]
        [Xunit.TraitAttribute("Description", "Confirmar pago exitoso y activar suscripcion")]
        [Xunit.TraitAttribute("Category", "QA-3")]
        [Xunit.TraitAttribute("Category", "Payment")]
        [Xunit.TraitAttribute("Category", "Critical")]
        public void ConfirmarPagoExitosoYActivarSuscripcion()
        {
            string[] tagsOfScenario = new string[] {
                    "QA-3",
                    "Payment",
                    "Critical"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Confirmar pago exitoso y activar suscripcion", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 22
    testRunner.Given("el webhook de Stripe notifica un pago exitoso con sessionId \"cs_test_abc123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
    testRunner.And("la sesion contiene metadata con builder_id=1 y plan_id=2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
    testRunner.When("el sistema procesa la confirmacion del pago", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
    testRunner.Then("la suscripcion del builder debe actualizarse a estado \"active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
    testRunner.And("la fecha de fin debe ser 1 mes despues de la fecha actual", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Webhook con pago fallido no activa la suscripcion")]
        [Xunit.TraitAttribute("FeatureTitle", "Renovacion de Plan de Suscripcion")]
        [Xunit.TraitAttribute("Description", "Webhook con pago fallido no activa la suscripcion")]
        [Xunit.TraitAttribute("Category", "QA-3")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public void WebhookConPagoFallidoNoActivaLaSuscripcion()
        {
            string[] tagsOfScenario = new string[] {
                    "QA-3",
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Webhook con pago fallido no activa la suscripcion", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  this.FeatureBackground();
#line hidden
#line 30
    testRunner.Given("el webhook de Stripe notifica un pago fallido con sessionId \"cs_test_failed\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
    testRunner.When("el sistema procesa la confirmacion del pago", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
    testRunner.Then("la suscripcion no debe modificarse", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
    testRunner.And("el sistema debe retornar estado \"pending\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RenovacionDePlanDeSuscripcionFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RenovacionDePlanDeSuscripcionFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
